name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

permissions:
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - uses: actions/setup-node@v6
              with:
                  node-version: lts/*
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install

            - name: Run tests
              run: pnpm test:ci

            - name: Run type checks
              run: pnpm typecheck

            - name: Build project
              run: pnpm build
